# Generated by Django 4.2.5 on 2023-09-26 06:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0003_alter_question_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="category",
        ),
    ]
