# Generated by Django 4.2.5 on 2023-10-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0005_question_isdeleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[("mcq", "MCQ"), ("coding", "Coding")],
                default="mcq",
                max_length=100,
            ),
        ),
    ]
