# Generated by Django 4.2.5 on 2023-10-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0002_assignmentenrollment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentenrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("attempted", "attempted"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
